# Generated by Django 2.2.6 on 2019-11-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
