# Generated by Django 2.2.6 on 2019-11-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_cart_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
